### PR TITLE
Added 1.2.3-r49254-k3.14.77-2020-08-31

### PR DESCRIPTION
**Pull request by jturn08**
Uploading stock firmware from Askey RT4230W REV6 with FW_VERSION=1.2.3

I wasn't sure where to get `expanded_rootfs.tgz` file, but it looks like it's just an uncompressed copy of `ubi0_1-ubi_rootfs.gz` ???

### CODE REVIEW

**Comment by Lanchon** [comment]
> Uploading stock firmware from Askey RT4230W REV6 with FW_VERSION=1.2.3

thanks!
 
> I wasn't sure where to get `expanded_rootfs.tgz` file, but it looks like it's just an uncompressed copy of `ubi0_1-ubi_rootfs.gz` ???

conceptually:
`ubi0_1-ubi_rootfs.gz` -> unzip the file -> mount the squashfs image -> tar the contained files -> zip the tar

but actually the "mount the squashfs image -> tar the contained files" part is handled by specialized tool for this sqfs-to-tar conversion. don't worry, i can massage and format your firmware myself. thanks!!

**Comment by Lanchon** [comment]
merged here: c66f6801f532ffb4d93f7e310239f8c819b86ef6

**Comment by Lanchon** [comment]
you uploaded ubi0_0 and ubi0_1, your current FW, from the ubi backup.

could you please also upload ubi2_0 and ubi2_1? your device has 2 FW slots for reliability. these volumes are the inactive FW found in the inactive FW slot. just drop the files in the root dir, commit, and push.

thanks!!

**Comment by jturn08** [comment]
> could you please also upload ubi2_0 and ubi2_1? your device has 2 FW slots for reliability. these volumes are the inactive FW found in the inactive FW slot. just drop the files in the root dir, commit, and push.

I checked and the `ubi2_0-kernel.gz` and `ubi2_1-ubi_rootfs.gz` files have the exact same SHA256 hash as the ubi0_0 and ubi_1 files I uploaded, so I assumed the inactive FW was an identical copy. Do you still want me to upload them?

**Comment by Lanchon** [comment]
thanks! no of course not. i thought they might have had an older fw. thanks again!

**Pull request closed without merging**
